pipeline {
    agent any

    tools {
        maven 'maven-3.9.6'
    }

    stages {
        stage('Build Jar') {
            steps {
                dir('dockerintegration') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('dockerintegration') {
                    bat 'docker build -t saikumar1605/docker-jenkins .'
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                dir('dockerintegration') {
                    withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'dockerhubpwd')]) {
                        bat 'docker login -u saikumar1605 -p %dockerhubpwd%'
                        bat 'docker push saikumar1605/docker-jenkins'
                    }
                }
            }
        }

        stage('Run Container') {
            steps{
                dir('dockerintegration') {
                    bat 'docker rm -f MessageContainer || exit 0'
                    bat 'docker pull saikumar1605/docker-jenkins'
                    bat 'docker run -d -p 9090:9090 --name MessageContainer saikumar1605/docker-jenkins'
                }
            }
        }
    }
}